// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndbamebusniisbniznia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYmFtZWJ1c25paXNibml6bmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODE3NDIsImV4cCI6MjA2MTk1Nzc0Mn0.qRwaqa3-oerOyRU-yfhdp6QFfTgyFdqfsGPA0faijIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);